crux-bphc/fest-manager

- app.js
- public/stylesheets/events.css
- public/stylesheets/style.css
- routes/events.js
- views/events.jade
- views/layout.jade
- views/mixins/event.jade
Need #8 to be done by someone.
> ui: Add /events page with dummy objects.

- views/index.jade
Still to ad code for fetching Google profile pics. @rogeredthat create an issue for it.
> ui: Add profile pics for Facebook and GitHub.

- public/scripts/index.js
- public/stylesheets/index.style.css
- views/index.jade
Review the first commit only. The second one is left over from grunt lining problems, which wouldn't happen in the future hopefully.
> Multi state

- public/stylesheets/login.style.css
- views/index.jade
- views/login.jade
> login: Switch to font-awesome icons.

- public/scripts/index.js
- public/stylesheets/index.style.css
- views/index.jade
changed topbar to navbar in html and css
> Navbar fix

- routes/api/services/bodies.js
- tools/destroy-and-rebuild-database
- views/account.jade
Adds dummy data for users, bodies and events.
Use like: `tools/destroy-and-rebuild-database [your-primary-email]`
> tools: Add destroy-and-rebuild-database. Fix bodies schema.

- .travis.yml
- Gruntfile.js
- package.json
- public/scripts/home.js
- tests/models/users.js
- tools/destroy-and-rebuild-database
- utils/mongoose.js
We finally have the testing framework ready for more tests to be written.
Travis had some bugs with MongoDB support and also, the NodeJS version we'd specified earlier was pre ES6 and didn't even have stuff like `array.find()`. Good thing we have this resolved. We shall be targetting NodeJS 6.x.x for release.
> Add save to database tests for Users.

- README.md
> docs: Change MongoDB instructions to be OS independent.

- .travis.yml
Note: cannot be easily tested. Just have faith in this one. :)
> travis: Cache node_modules for faster builds.

- public/scripts/index.js
- views/index.jade
> bugfix: Make immersive event exit to the previous page on hitting close

- routes/api/services/users.js
- utils/authentication.js
- views/index.jade
all modified index.jade for prioritizing google profile picture over github
> ADDED: Google Profile Picture support

- public/stylesheets/index.style.css
- views/account.jade
- views/mixins/form.jade
> style: Add consistent styling to select and textarea

- Gruntfile.js
- README.md
- package.json
Also, its a losing battle against npm trying to format package.json with 2 spaces and Abhilash trying to format it with tabs. I let npm have this victory and removed package.json from grunt task list. :3
> tools: Add nodemon support.

- public/scripts/index.js
- views/index.jade
Bugfix cause first PR missed this.
> submenu: Hide submenu properly.

- routes/api/services/users.js
- routes/components/custom/pybits.js
- routes/components/dashboard.js
- utils/authentication.js
This builds on top of Sohail's work but moves the relevant code over to `routes/components/dashboard.js` so that the QR Data is not stored in the database but instead is rendered as and when needed.
> qrcode: Shift logic to components/dashboard.js.

- public/static/stylesheets/about.style.css
- views/about/contact.jade
Makes minor changes to show in two columns. Also, I've put the prez
and the gensec at the bottom as they don't need to be contacted.
> contacts: Add temporary contacts of fest officials.

- app.js
- public/static/scripts/index.js
- public/static/scripts/register.js
- public/static/scripts/typeahead.js
- routes/api/services/events.js
- routes/api/services/users.js
- routes/components/ca.js
- routes/components/portals.js
- routes/upload.js
This primarily adds a better logging format so that we can easily debug the server logs and monitor live traffic.
1. Show date and in IST.
2. Show logged in user's email.
3. Hide resuests for static resources.
4. Hide random console.log outputs.
Sample log line now: `(Sep 13, 2017, 11:37:21 AM IST) aero31aero@gmail.com 	 GET /components/dashboard 304 205.113 ms - -`
> logging: Improve log output format. Remove random console.log statements.

- app.js
- dev-config.js
- routes/auth.js
- routes/components/login.js
- utils/authentication.js
- views/index.jade
WARNING: This is a breaking change. When this gets deployed, we have to make slight changes to the config file on server as done in dev-config.js
> authentication: Make auth backend optional and easy to disable/enable.

- Gruntfile.js
- tools/destroy-and-rebuild-database
- tools/manage-user
- tools/migrate
`tools/manageuser superuser one@email two@email three@email` and so on.
> Review, merge and deploy. Should ease creating new sueprusers into one single command as follows:

- routes/api/typeahead.js
Didn't remove fuzzy but added the non fuzzy options and gave them higher priority. Thus, we now get the best of both worlds, but slightly slowly (our forte). Anyway, review and merge and I'll push.
> typeahead: Add simple string matching search.

- app.js
- routes/components/portals.js
- utils/service.constructor.js
This secures the routes as well as adds a central point of communication for our portals, instead of the current haphazard way we've written the existing work.
Would merge after one positive review.
> api: Add authentication, revoke public access. Remove header restriction.

- Gruntfile.js
- tools/cat-user
See usage and check if it works on your db. If yes, merge.
> tools: Add cat-user script.

- routes/api/prelims.js
Untested code cause I don't have the docs key.
> prelims: Split route by events. Run grunt.

- forms/leaderboard.js
- public/static/scripts/home.js
- public/static/scripts/leaderboard.js
- routes/api/index.js
- routes/api/services/events.js
- routes/api/services/leaderboard.js
- routes/api/typeahead.js
- routes/components/custom.js
- routes/components/custom/scores.js
- routes/components/portals.js
- views/portals/leaderboard.jade
- views/portals/scores.jade
- views/scores.jade
This PR adds an API endpoint and corresponding portal for adding a leaderboard.
@TheGamer007 is working on adding the corresponding endpoint for viewing this in the Android app.
Basic overall feature checklist.
**MERGE THIS AFTER REVIEW QUICKLY**
> Live scores 1

- package.json
- routes/api/index.js
- routes/api/services/accomm.js
- routes/api/services/bodies.js
- routes/api/services/events.js
- routes/api/services/feed.js
- routes/api/services/leaderboard.js
- routes/api/services/news.js
- routes/api/services/teams.js
- routes/api/services/users.js
- utils/service.constructor.js
Adds a dependency, so while deplyoing, `npm install`. Do a code review.
> Misc Stuff. Requesting fast merge.

- app.js
- routes/api/services/events.js
- routes/components/portals.js
- utils/config-loader.js
- utils/service.constructor.js
- utils/sort.js
Run grunt. Add two details to /api/events/index.
Fixes #264.
> api: Implement sorting in GET / calls. Other minor fixes.

- public/static/scripts/prelims.js
Changes in the Submit Button. Changes made in prelims.js file.
>   Changes in Submit button

- public/static/stylesheets/login.style.css
- views/login.jade
I have added module-login class to it. Please check and tell if it is correct.
> Added module-login class to the file

- public/static/data/slideshow.json
Just check the structure once. I'm not very sure I got it correct.
> Made a dummy json with 3 photos from r/travel

- public/static/stylesheets/events.style.css
- views/events/event.jade
- views/events/home.jade
- views/events/schedule.jade
Schedule page doesn't seem to be working. Rest all is fine as far as I could try out.
> Added module-events to these files

- public/static/stylesheets/about.style.css
- public/static/stylesheets/contact.style.css
- public/static/stylesheets/events.style.css
- views/about/accommodation.jade
- views/about/contact.jade
- views/about/credits.jade
- views/about/home.jade
- views/about/privacy.jade
- views/about/service.jade
- views/about/sponsors.jade
Please check the @media tags. Page works fine, still, check for spacing errors because I am not very confident.
> css:Added module-about and module-contact to about pages. Fixed @media tags in events page

- tools/destroy-and-rebuild-database
> Fix: Add timestamp and correct format for dates

- public/static/stylesheets/home.style.css
Now it will be visible on small screens.
> frontend: set background color black of landing page for small screens
